"""
Django settings for SLMproject project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-%a_htvvnfx_k0yi*cgmzbu0^t62$zezoyje-07*0!r)oo1rsvx"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["slmpro.pythonanywhere.com","192.168.1.60"]


# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "SLMapp",
    "rest_framework",
    "accounts",
    'rest_framework_simplejwt.token_blacklist',
     "corsheaders",
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}
AUTH_USER_MODEL = "accounts.CustomUser"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
]

ROOT_URLCONF = "SLMproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "SLMproject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

# Source folders for static files (development)
STATICFILES_DIRS = [
    BASE_DIR / "SLMapp" / "static",  # only your app's static folder
]

# Target folder for collectstatic (production)
STATIC_ROOT = BASE_DIR / "staticfiles"

from datetime import timedelta
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=8),   # 8 hours
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),   # you can adjust (default 1 day)
    "ROTATE_REFRESH_TOKENS": False,                # optional
    "BLACKLIST_AFTER_ROTATION": True,              # optional
}
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",
#      "http://192.168.1.60:5173",
# ]

CORS_ALLOWED_ORIGINS = [
   "https://slmfront.vercel.app/"
]

CORS_ALLOW_ALL_ORIGIN = True
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"





MUX_ACCOUNTS = {

    "mux1": {
        "key_id": "8p8bq00YDZ6uharwJ01yTqHiv2exqhrxRRzCWeiaMNinI",
        "private_key": """-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAqW7QHcgX175WbPEPgNx3H+genNhwqdWayAwbE/HAecrjPdZ2
8pIoWjo1vYq9sWHiDvmDKfdPn0IVwjVbZDFYEu4VrQB7XjryncS/xoyDutqbWKxi
I9w8mdtqfqP5HGBYyRwPFagJvl6eTEDvwo8BdqX6fvtANiN6DMuK0LpaqwW65jp8
wItNH7rFbn71pGa6+/JxmlbMre6MXAO0nkH7otSY/JIDOyUTtGXDfdGbJVMDvTA1
vblU9NcKSudMS5/nHJK56SkUVX4AaDqGO+UtFC9O+isKxNBx/J6vu2Ftj9jwwgNs
Q0oRve07b1SFXr2UjwOARcwp3fH8k4yCzUObbQIDAQABAoIBABkERBVJoH+Z2m/u
beAUbUBYSQDWklf5MofcBbl9pfI1qzTLsDdjrjKYSqwISrbgoXydiajOG8MDgmvw
7eQOxxbQcYHgQtbodD8oODqsL50MvwgqN7lcwNPkykYVlugCL8nN60pCy+GAXfYb
VmtPKyOmISTTmykDNvehrAbipRWAHv5ShdDhHHiyiZVMae2oI+lil77DkPxEbxJ5
o3ZP+03AQWFo91eO0e7Gbt6CD3KWpLu6LQfS+if5YFaVOrfUCkafFRKdmbBjHam+
r9xiDSCdBBHuCBCBKwzl3G6LFmExZ65udZ1IuK/nV6ixLuO/VFB6Y23OutrQdwK1
YPGzzw8CgYEA3CMCkXFvaVtfZ1Sq4aospDIDgiV7LkJkwS7FINh8yC3S9cNMrAH0
5ewWB7pKL6tumSzxoBT17aVq3I9svLOFpWnBYXZDVvdCu1IodX2BPPj7ywj3QVUb
GiQHDIvHtsfdF7gD6uX1hf3YP02DhyPc4MdhKeOp7BfNnm9u+93DGccCgYEAxQkn
bvt744HtENPkeYNb5dTizUrkAxAAzz14MyFw+cpWkhNxbDco+ElGJxH8VFLGXfyz
3qoFDeQJlSmc1vhyq1h87thWeSbq4egsc8rkodGtOH3WwUl5OIVFoPq6WWyfzEqq
aKzBSx2JVgc0ur4y4r55nHJLSIOOti55ya53gSsCgYAJQrvH7JK4RuzDhw9NQQBx
w9zb68G713Uvn00RranKLgtS5W1jSw3HYmAm4RJf4QFdFkPv7RHPdocBUlNLuO2l
YMaO2A/LJ8m54aHsF2SJcRv+lZj5OaBTQDK/t12mdc/6QHaBujzS7zPareMbm0me
dyTCQ16RnQq8YIm1tMWRXwKBgDdplqR4p2PZQ1GLNeMSlUKyt0IjALL3yjJ+SBKh
IgOt6uDUBP75GFWTTd5pCXyxdsYx7mf9isRYUHWZqVkvsBgOH7yQLOmPj1kPEYlT
Ey+LJ1sO0Nm1DxldKbLXMJc7nEk46mnbw9SbLud5yVOHcAoipVLhNdjj3rvPoEKf
BU7XAoGBAMJQrGUdqjxmnybVM2SGpHyf4bKUPn+4lbqml5lAMRtIUUinLcLppdHh
oemma4Sm+yOhXYDvN3yY1WTCAPlQ+WE/m117+PL47FIfeT5LkExlgpiqZYlDRrzy
8FyKyMZk7vU44ahmmUR7wm9Ya+W/YEPidLIzbF3FU87Yiw/JBOou
-----END RSA PRIVATE KEY-----"""
    },

    "mux2": {
        "key_id": "WI8ksNcJhN6Jv9uNP38i01dNbFXN023L86V48jKcQxeV00",
        "private_key": """-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEA15oVp9leKyTyX6+vFPgS10AXIvfI6M+pGpYszSc1pube/pZd
PfdiTNyzHWX7llVGUkThOLMZJ2O977iV988xlTg0xswTf6Gj0kgiYFB1RjPHTYey
EHP0ovHPkx7OwokgMvKSEUtIliiql0y4E/jU1ZXPmHGQwXBmLLauLY/leAF4WS+E
Df2SebanRx/fp15Bq61qRe/LqFJHBv7FN3fyj+kWilTZpfdHHwWOxvSy9bUpNQ7R
dVFXxidvo2WujFWZtbHaJfG4IiyaagjwtaNhfoPlKpt8FOMNLBeu3X+tT+vOMpUv
B1Rw8ysYuMEiwkCoxX+oXvggUIEpXrU/vwp9DwIDAQABAoIBACzO8MZAJlKYLKlX
VW9puVy0DLrvPXmpQu9sG6aNihiEbf8CWCGbSvpHehBXlCij02gguaAzlLw7fguW
1NA6ZwcotctFOZ4yhV4cMMzMm/r5oufJlmfV+Zdt4yKj6fvDTQZZpKLkfxL6I64r
Oyynb/Bt4MXBgIC7b/jGBMAiYmIEpkF7Az6hEpdII+6aHfsgU+ASdPHCAMV9EXQ7
Xw2HV5ySBevG70uJ6u7xkMAjcNbSPVLSTbLUH2p+x58bU8Qofac53rU/jUq7482q
xVFd2CZRbW+w0Z14qHbg1VokWKSj47EVbY0z75QzAecgw8ZS0wOTNLHarmiGGMb3
/W3zNfkCgYEA/byD+D762IuF1G6zb0ANIuvlyXnkiH1lC/GHVwIcL5kcDGcOCtwr
KDKex6LBYAe34VLduPTYwycKYsjGpSyC5wSSSl/GnzkRZ/M0MKuFJLukyQS5x02+
xyCNOEOOlZIKHZpOej+1ctcB98kgmhnfSgI9bN5O7wvg/Tu4FnLEmikCgYEA2YZ6
MfI1RZdEmf6pV+ZDY+OgGfwFDM1/rx6pIQmHru4WOm+Rqu1ypZMpcg09EdZCS0Zi
9+iSU0vugG/r/vZIfbaq3QxfeCjFhL01UfZ+LViaHg2v/LOgjHXqhW5juovF4q89
3rDLZn75i/QPQhbpveWCQzntcTlqC8UmG8tytHcCgYEAoqHwHG+RrLZRA0YpMIdn
ZBi7YhYEyw9EcxFOZBBwLHoAplpvf7p61vsLFn5VX83SqFPK1b/qJ7ugRozV9gy/
on8lnRIiZu/XHj+eFgv5/P9gsY+b3AkS3OMaYRO8ElZWsX60CltHW+I/2qhJgzxO
CEvDP0KGaWW9wdJDPfA133ECgYBL2u9l13boS7XqlbnsIypA/THpnc8NBeSO5vxH
vxEH2ZL60clUd/VQ9B6x3Rf8zmDT6zm8BehxD7ueImmDwdLJtBelehkYx+8JOQoN
CQ47NfiYnmFOmD1WfhBIc5RnizJ4uG+05qYnmgPf4D4p59+fDxf75Yl9wG3QqPF/
I9VeRQKBgBwQ2SoQiP22VRlsVXK02Th89QzU1KCZ0LMdw+aNNOwknt6lci0FnA/u
a8OTn/685iep6Ib3wOQkkVdsBVLossdgbE35eC6Wb3PhRDl65EpEsaZLm3pqB6FC
hovRRCIMTv0e6DlXkEoEh+cP2+5DAI1QgPhuE2UlHEzC0sMSZBme
-----END RSA PRIVATE KEY-----"""
    }
,"mux3": {
        "key_id": "DVAx01HcXjDDiHSw9rDJKn8YxCXZkm2I2OqPnfx702OfM",
        "private_key": """-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAtgJwxhZaqxXdS8NG+6mWd/xXN5qOEW7T0Hqvh6GAGKo344da
YtKq564Tt3+B1qobtaUDuBxmWHtQpMgf+eJC3ssxIrOQM1erlY5j1qWPhCrMUNvx
nrYpPCuJAugn+KQ/2RfIaTTofC7hT433ooyS3xzR/9bi89mBtXoE+j9cqA8NILE8
kD73zL/Mbg3rsNlKH1FXSWYDC3ERsB3obbNRSZzupDh6ATDBzxklE6Vcdtc8j3sf
/OF06OfXbothqbvNpV1n4vG+hZExuJm2o0sAx92Qf3nreka1mhlDK1i/KEyRKY/g
KwbuUy/ZyDjZ+XkM8wO5XPVe5r26mSCxgsTgiwIDAQABAoIBABufPzIwzk3MoasP
1cP3tsg62ZmssQbgRPEMzXrN/bzAiH7VWdhJlHpYptFgXnoPkuj8RBY66SVggZqg
bInl1rQtLiXQDoBcO8QUuf4nXiJ2xE85MfAeQR/Kk56HURmhA7eUrmuZBfdivfru
1rgqkVee7hffqs3LIq5B+GNqHku6y3pC66alNEu1qhBRmvbMjN/MP4/mT41r15zG
hFnh4kYVpyWtq9lZnXEZ5Wqho708KK7sPTfC6P6pnrb2j1ReOpCo5g7N2xwCCD/e
+cKTXbiUZYH9lDHPa8lVapxjBUrLmWRHpKSPHhbsnd5tPi36bzX6CxttxBGEParb
5c8aYQECgYEA34JOhuFIyPEJ81KtpUIK7KMbPbxOWvbtzlkOPJYu+RoerI+uq41f
xOVSaYaShCQEaaa+FZTqjVJYjf/rEHRUao5VKcYD48buAxtp2dofqyUXV1iZGEak
BuU56emlb5B9ygtowMKnCW02OM9MzDQxULlSNFCtyMWgyzDxi8F7BcsCgYEA0HfE
UG/7aNm0J7bZHMbYkPRH0yAd5kW9xFP4HegjaEyHVojBKE6CNMzCf4OgPthcK1IJ
5MaT5J0HtboPZjAPv137j4HhMW/l8UE3O7kHFh0ID7O+2EMj5w41D5jCWcpWDp+y
PnGYZnejvjyJGPYd9LzTuYSCfX1ns8RkdiNMOEECgYEAwkO+ARnaa1ylq2mXJ+YJ
HLh/ut7qs8Gf3BQnfZ2DYlvDgXS4+r68GKTBRpsCyfuMIlAdMyDl5MNH2NQw+XJC
1QK1HsPPKbEDuoufKwydLeHlMbP+DM2JT7z440iC1D8gNfZIrBIDoPvdfu8e7vYG
TwVkX7gn9DNhmHoH19LpHJUCgYEAnAIVKzEyj1vkw5fF0RBKP+hf2/L8DTkB8+v3
EcKIxOQIoEzFaLmgHY1ivPSvNnjKOS0y9D9brEmL3Ia6QXoUPt1BhjrnYQzhovNw
N0SXtgfR4ZZdaxCLzL1IHjzurS2Ly3Pde3edWomMQ7Cf1MtSzbWGKR6uXOU9dz2x
BOwTfUECgYA+Zv8jYMReXCZuKKo80QVcF1c2A+kp9w3obdrTa95pAUfyqW2h8dxK
CuG/67BD9ixROP5KUXAOOCstigrYAGnLDt2UAqzNQEy7RCP4v32dWNMaMb58pHOn
V5PezThQUSTzrRVQg3dM1kffFp/2N7J+g7vzVJXm4HUFJrfCH7Tf5w==
-----END RSA PRIVATE KEY-----"""
    }
,"mux4": {
        "key_id": "H9N49OjgM998scsyk8bCGDq5oTLyIt02jYvJYf6ZDbfg",
        "private_key": """-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEA2rTSLWGTCIEgZSS+edbK8VmRZ1vhEOd2ANYT5WqAJjGEC8e4
AAbPcRQazpxqEN5upVS9ujvNxbytDMv9VHK+pqW/drkn1brqf5Jh/OqVGHZTb621
DuG3hef2Ug/S0nwADTPEsuzSAgQjs0d5ucgT+3URZYV18mlc2YNB7QkjQdfyOFHh
QEKQPAi0unxg00hDGFLjurxDStGJAoLY4E+ohzX4PtiaISEqdk2lo3cwCRpGZ1WG
VnS+WrCDmCopucOsr8Cplxik/33t2SutkKXfdUXYRscfeFZBuV1P26CNonzxPSEu
rCf3xQGa2tjdemobzr+N/N0DPIcVXpk5Ug9CvwIDAQABAoIBAFdRaTaYJeF32Gy5
Wlj/sj/g4EYxby7WEo1r6z6loitdipg/cU2Fao39lmRWG5zHicp1hlhT5yhi135r
9SUhuM+FDmfCrc5N1bEASyH0sHk3SMGmS0r5QFH0lioWSjgiLM0YlZhQJ9qJN42s
5EMRyDSVfVAYlEon2du35XrTMqHm7krMn4OBp1XAgOlYqeQt0g91KtM5hUyFg3Xy
zc/VCh8DQ36frEOWBvJ6OSuvFrLtwq812kac5MGudRyWYJyl+jN1F3GAGn0kMZkJ
8RQzeC3D5RrqXL69R8d2FQBgS1j09pkrbE8rAbvS3VWZi7SNIj7SnetTe0fY8BQv
u9amSvECgYEA7b0CPPfwo9U3jkx5Fk/aa3HbkT8WUMhAEkyc8LU/yRtd8AKaqPGN
cF8dHZVTxv/5/MB1LeHwVl50JF+hG62wOgaUz9JWJllB/1uHskqJBypdNn8Aw4P3
SZqPhRznS07Mj3nJImaoPuE3qXsQk7Mci7kSJ3aS8lQC+iUp2jtVX28CgYEA64GP
FkwxWr6/Cx/ZRtsTat7S6oQFFKGBtPr6u/acsomHfwH99Ok1ZTXlBJ/bWSqBFBcf
GrWeEhFE4Y0pPour6BepohUwCPxu43oMqviofIcAJNUUy4JjeXm4zlEIo2ytyeL8
GqrlWmsZUCGfJ19hVolN9hf95IP+jqI8owx4qbECgYAcAEIOOkm+kjNr8Dfm19rr
AssQrXSMaTmarilh9IchwbZruXLL6T92d81vGZJ3gtjH20cx80WidpeJXTYVk3yJ
KRNH8wcwlxy93eL6req7zFKUQ5ssbBOpOKokzIW1if9v+rEk+yBf35j1vkfyjYsU
LeUkfsPKBPkgy1XFnW1twwKBgQCqP5nCA8i2EiinkRmQiHUMEBMnZ9MIbA0JWVqD
IS98PcHPBhChySlJhmGOK0X1uq1faauZsmuYIhXKfDKxvWTDvr9ppal5BYvgNG4N
9v5OL4XiGowS5qqkuWLo+1mkUr97r/SSDrMI312IORYF74S9ezr5ybRIS0dts0jk
kfJ0sQKBgDE7Q2y0O2pNrNmiOn9iQ0nSNKCpk/3caxLum13T5QLX9ozojXgkv+0/
RpK+yIk3TAnGM5eJZfgWXWGm+JQIqkXMuryaopwgIYMtFtDmL858tj0+JAz+0Po1
OqR6SuT01g1wc1Y0BFw34FbI20qEB7tzZny5diP9mLg5H3ig0v7Q
-----END RSA PRIVATE KEY-----"""
    }
,"mux5": {
        "key_id": "1NzrGWz00zKU97HeApmRVEA00TdUXVFkao01AxnXWHOB7E",
        "private_key": """-----BEGIN RSA PRIVATE KEY-----
MIIEogIBAAKCAQEAy1q52phFc840SIcBw0sjb5D/DF3O9ZNxnpfuHpOLL8y85V6W
B30ig0gnAh1GGno7zXdecW/iOaVPCQZIWxWeEGmh5uG0r6bua6xzPRP97AJIgQTk
r78J3SOh7nnjpb5YbeowZ6eI60XRq347MV5cWrvA3urR9XtTpuylK/wQN1B0S/11
sdOwuWxjdcivcYSf6iqwqhHr7BWq4c6D0R93iECpVY371D7onl6AwXabo82uYSy2
0xz/JpRNVBzRFxdNDjRvVFHBydHYp1wOqrtce7+ZDfamJWw/fUs99E/Yel+yJfX2
bTu11LjgIAgR0CMC9UO+1Pc1Kel95dKXQvvJ9wIDAQABAoIBAAKJ/3XI+hUFy88J
u+4vvWqrxMyeKGCEBH4EJ54esFmj3e7IX44KqxXvZ41IWW6WoUP0EHU+tPRn4JAu
kZ1IYz6RN6aTfSl9cKpeXNshzenWwgfaXqUuiyxp98THEx5MYiCPfks6vpHDv7FN
nZ1N5yuWR/tb/F6PuVup6wqc+xbaRJm8BJRa0VC+DSNM+gz1Bv902HJpJd2b9OAQ
hF41lOsguCG1Mhm+goZfvnVgyQrCKyq/S2usRWyIpSuR0rf/nLOsaprxwuAqQ4KH
9EoyEHmdu3Uvk+btVQ2f5WUOa98+G19Mb+qVzWuSUqRheHmhkxlU1zcNgHg5WtFe
FW3lxAECgYEA9aGufykbHW422mHcGd84lDjljmOv9/qczjJ1YW/Cxukqi7crhZeB
FjxWpC1khnwHk0MdLZ1MN6XifrtfOR+g92ikiQOsAqvIZrYWrGLGnRuGkoMMRTtg
0kyGs75M++xbjCrkR8so0WakglF9Ktb1MdMCoIc0tCENSi4wISNdd/ECgYEA0/Ax
dPzA0AjnihXD8CO/XfRbsHOmKCz4FbTP4bTGQkbMKEz8cZA3H4OlGTAyCmSfyGrg
jlwrQHUkZwVkB06wN0zmP4r9qzUZdRcoyrnPzOI2uR2hdQv7haajaqDLgnhNV2sK
D9UzbUvV/3a7FNdJTEqs7NFKKW7naCOwER+xCGcCgYAWD4VailiTFhj7GBrqf+/W
8B094polTW7T3hhIvf7iWoKltbfE8cx4MMcfS6xhn7YWdcqjFCOKQ+3JsA5nVP3h
+pX8cEX8n20KPIRgyyZHafd2JSru9NxHRvQ6JHdJkPrP5fJGuGpcFDnmMmdpd5Dh
/q+Xt0z2eJl29hsAfuqgIQKBgBf1spGoNWAPcaWhukn+sJa9llQHbwRhuRYzH8FD
f5pkiJYRxgRMqn6sklCbqzyTjaDJvGM7tkQOOjRPXrSYx8Eot2r9mpntYdhj6t+o
S/68oDUjTWp/FUtRwG3AieFRGmVEm5mYn7y+cw3zbUj44bd3Rb9sFbdDa3PRfQki
jRAHAoGAdRwQaIN/13BtxWd9t3YtWx7jTZrTjiTP6HqciEU1+sxfyzKfe193JfIO
H0/rYB2JEhG1tivJmxLgDxK6sliLVA73Q1fQ2di8HincnO+TCBFu3s7R9D8AaKlS
VvkhVIjo7TWCssJsaimO7faNLHGs5ZBX5ByMt2o366G51Q8MNug=
-----END RSA PRIVATE KEY-----"""
    }
,"mux6": {
        "key_id": "CfQg4iSYK2t4yZxlCWK01nH00v8wM0202zXpyxeCpdJV02aw",
        "private_key": """-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAsi/1jmxBfprKuxyk3AmMCKX/y2f4rey5YrnuXbrle/9BU/jd
PIU7EwXWd2tMePORIJp76jyl7m+iAoid7MZf5fkhboH2HLUUU0Lqak7H4pXl5pCK
wjPN1f6EUjFmZPrs7fIoKU81SBP1xaunqW3mv2b3MvwYRndScKMlL1LWuHjPiroL
2nVebHknTTum4Ji1XHkY1IZn9oZYR0o6yklxi9nhLK1CqGgnhi4i7hReIff48KQ+
JSrzqtmkEIrc07u7ngJ2WJsgWLo4lGhaIeT2OnSjkueXx67+3fLuHeUinSehASo7
kk6aCq18gMY8Zg8qaf0TO+i7U1ouiJ3l02ycGwIDAQABAoIBAExIRNcmmDlTmjPV
dOxwN99h9WqGhcsrm0fdMmM1BlZ5teV1lnz4yov/xUtVh6UGHNy41hC2yxCTAOgV
xYoeeOKSr5HIGG08xklIzeMZ+++QXZ5Bxe2S0O1qawpm9J+JXtIVB8V7j+NeDCsG
LB5YGt9Y/L36d4f/QC9RYLNsQtkww4jHi6StGnn7c05QBLJ8jb1vXWzxwidhxHNF
neqP5EGmmY3//+q1wVSf52gbR+li1FRj/RT2dM6Xm/iDlpX6/BOOWCQqxAxBtWj9
p3NDCg3UcvgJnl7vC9ytwJZBNTgqrnNQwUsxb8h7nVG8xwwF8lKdgKwgi1nW8bbU
GvG158kCgYEAwzUWFFM8ST3VXD3HWgs49gc/dFIAnxUwlCpPT406HDqNy69uNjiF
8URtQhKMMZ+ykMyzf5TePa0IiKzs/H4i4T3fHcUs38vP/yeOW+rNe8UVCmORv8xw
ojgXypFfHkT3vWoMSreaLlwRcwkPGhWxGZ0foS1HjPJMwEcaGQ4AIUkCgYEA6a3z
YdlKYZzBGSnI1DL75YJ7QNKNKlwlbkwkz+QTU63pYN2JOygnoV6r1SDDDu0HjNrr
TB7qFRKDB04a9Arj2dPkOdE6EUbIOHXz3IKg5z7yMreuXYWSKaUNUPq+fjKyFIGo
sNLxPDsrACcmcx4F+/Rz+TPjJq8G+9i45H3qtkMCgYAIQCwou8PmjJiCB5Jved30
eCX0cqrYDns5J/imMh/spYTswQN1gzoWEoBTtJj8V/WiLSTBFbe2/6NGs5hoq6Qp
xQWzKmxVITYvYKqhs/DvdEsJX1//rVJtaNWImFBe5SdbeCoA1nXL09Rg+lcLETOl
E4EMvO8zQ+J+lgLCYFcdEQKBgQDeNmWX6dqaokbZ1+s7JtR1NrRgOxi0bHXHwi7L
Znaef2XLkD98er3c7Tr37DSxD+O7JT7V3xv4N+dT3gkxgt2TebSw6m6OmUGyty/T
xICgBjKo2hS8qFUKtwLHu/nD5g+EApxYse9muFk2xwQAOk+0fYx/MMFUOuKoQTnp
RngZIwKBgQCFEr9UT5OZjn/Uv2ilXHtiCt0F4S5atFcEKVQ2sJGgLy/ePIeIa5UI
Y4h4F+skiWChc57fPb8eIicZwEpqy6G3PKMrcjZScZCYNY5b9TEpOWQ1ZMWcBp5B
DHtceUDslJbedf13xlB7qAIkRdiiWAxi2Aj8PQJR5fT/U3dvKmwZ6Q==
-----END RSA PRIVATE KEY-----"""
    }
,"mux7": {
        "key_id": "8xyRLSZ01gGNUiPorc2kZo9RhHt02pWoEHFeQr4GZHQSs",
        "private_key": """-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAvOOgS2adKKszP5LnMqQrbf9/y3Rs8kAbMkoOLtiYsVbq8wjM
WhYh2XDRyHAlB360TxSysi9oU/vdzSTbvTN9SGxT73iQRhc39OQZYu6E28bTW38A
Jy0seHzy9vaXNYXF20TVBziu7fF7e9minU8+tA7Mt/PZ5RzGqRrBIJayYDOFHeHn
TDjtcIiT98qm1hcrk58THY/jPlFpKsGkQkvtedxuwWhEVtKZXun3RcnMTe+wJOru
+jxU8oqd71bNfcOrAxjfH0dF+9jZzY4oGy9Pro0bR0Jl+iqwjpvwVtQYtjA0w6oK
koZID/f4x6r9WXlieJTx/snwKnC1En+JarbgkQIDAQABAoIBAAJZjWl8DYWKH1qh
p0HmZYUVAL1dQEuMCofn1duVavfeJOaGBAnKXPHa1mdD5Y1dcTI10mpxo8lTWK09
cZozKT0KM59G52TnKMrBftiFLwQEv2Vz3o1TjD+JpA74XsWbZDcv45EMjoOMBaKI
Vh6Bc/5IMVndUnHS15ysBiieQKTo9agZtoyrjTau2VMp5yILIgnHFwRsE2jk4jL2
81Qhn8UpVG+2bovil9enhMAwcRUq9GzD6WTBcUWhl0m7VFMDbbfPXzM7tNwjb4XL
iPwKOv2i3VjZuW3ONo2Ykfc8KHSjea4fGJJ2aUY6uLtXxm550KX3+lMhWsrsHG8s
kBVXDEkCgYEAwwKyGrJiW/V1Ksn6GwMfzrDOUEtn8ZQkPhPVOesABfFvjjqageDk
m0u8M6KZjAxO4bZx+3RUtfRF4HY/+mb1p7BZwKWzh83BD8cJU8rVYz4z7ZHdS3jp
gtik7DQqOgoc+OJTWO3y790XGYQFl3Uea6UedTatdqNRFVtdIbMGW1kCgYEA9/bU
e75tKrd2KSidT4OZJp5Zjvfb4OAUM8+3euRL5Wb6sekjvWppbUvi0FrDu0vO6Kjm
uOI7gJCLBcY+VNvgerLJ5X2SF2DGtsk7W4uC+3YIWwArYlKUz9U/XDh/+D+VlkFP
JkZXlZfyo2a0/6i/xVkA1EZSRWVLVz/Q6EByX/kCgYEAnFxY+lb1zs4tODXiuC31
HwFdK7yKh4VE2hGE8n+e8ST5UY1jvafZJTvAl5ZUj5p+1TQ4iGpqUcqfDK9D9T8A
0YfxLyqtnMI5frEUpX8JQh3p/R7r1UwJz8Rt2IarJQZe3KB8O93u4KzhjK/y29Io
ph8rIMjKpUmmBf3P2ul0u2ECgYAOILweiM0DgAx1b+D2pNLXBnKn2KtodpvwD8eu
cs94NJPYCyaEJkn3djloEaPRShJx4x2yLwGg45toKtFmWFjD5Ofn8W2fc14fD/wX
zS0bUrBLLwlJwtbDuKyxfm6cIFNPik0OKzfWSCAE+1cYse6rOdT4Q0FwvsK6J+Kp
OPLLUQKBgQCX32CJIblVKy/IMRHlPeK8FTp3I/QtEwn8T1/QzDodl90mT7shO7FL
V7aMvTW2luRQa7jSUyncyEPEbW7zSwVR7VvTf1KM0sJ9fv5sE6CY+ybYRLxGD1Hd
gBHXOT6mADW0a2eJQ9/y9aqzINOPzwxYEfTpGNJhVcoL8KZUdtTkAw==
-----END RSA PRIVATE KEY-----"""
    }
,"mux8": {
        "key_id": "wL9Qjso3X3UdOVgpS6La6Pl01VVLcVZJSExanNvzy01Tg",
        "private_key": """-----BEGIN RSA PRIVATE KEY-----
MIIEoAIBAAKCAQEAvr6VotjWF8v3oHzTSYdXXWhRLujTrAYBj90YzugY4HlyciPD
pdBlQJXpACK9zk21MbfsAzW0WljDgv37hsAUVODhz/5rXDr9gdA2vDLsTE6zA18X
a3A+R8oWIWS6Lo/yD8hSakYtjhaI4jzqeywLYyQqjy3BQj2Fi/EycwwIdE5JJFsD
e4CcjZKDu8oST9k57TWm7LGTzcieUW/XLhXAvKkIoQAXKTJV/8uGT/CLTU2MMw18
8BdwJgMSvk5zNCbe+364H0dlkrW9lqg1a1QgEH1HFEVQaFkU4IT4CWOJvKGZ56MD
R38XDev+ORwAKPJ0xOLsD0PJvYz07K7tCfQpwQIDAQABAoH/E1n7cNhHw7679gUl
v8jXxf6rzA9vaif48l+DHbOZC2XxhLEqaD18QSaCkl1luZ3FEngBDxlq1k3j+cKg
EEuzi3coxwaeJODXOttsB4E/hikEDpOB0916Ak6FcEFraT+xVkwgEGEAE3+ZVVqR
qFDzLCLboEd89204NJ31lag4M1t0Vi5C21FsassjReL5evRiGPQg8WTtpXdMLUsm
xICrHdiiR7rvx9iA5vZy0UNUN34WGj5twP5om6P4jMhUWwYs6rDtjaGAoORon39y
Awc8q3luiMINzqhhpNW1hz6rij0hNh9IjEfHQJq9OdkgXKco2uUwsN7fNgCHgkI8
FAgBAoGBAMW25GJYbkyL9FXzjw69fnHywS0tPASxOh74gwJMmVcAlDr3FUGSZW/8
X//I6cAUsd8TBJZkm2N4Z/Afeq32kja40vb2ZdLqY9boNvcbUG68G6+xiTECR3W8
puX8QmrEs2yrenl+qZcgUZ/l62gWkHJHDqumiunj2/15M/2jj4ZBAoGBAPb5rymq
pDjhFmGyFhNlDhg8IcAJtLTE42EwmaV1dezNu9CGS0OMWdc/tuwVO5ABsQ57PW93
Kn/D2MiUqbLnaItF5w5tBkKd281XeZrCuK8acZC68XcxDmSWGZCGmhmydn9ROL5R
pr/yl3CytKZt0K9ztJe45Jw9gA2Fcw8f3sOBAoGAU+LbV5aphbTDwEwMYHap1XLn
32EX2+3N+SH7g9g4Hx/RxIrc6+tPOopbuMzn0GV3amxJP/4Dp9qITussQ+8f7jPQ
3pOAdFKada4k1Ac0wybwoES1LqQG6b9XGLFFBMPcVLkUx8Oj9MjzmOIWVR1tv+7C
HLYWrlHNHuhz1KO224ECgYBd3JiogjS1dT33VSI0rsRDi57cCBRIW0d7KWhLTK/L
lojZgCBchJukRY+0e4FOgoYS1d2MXkKlmf3qhS1VU8MUozVj8yVc7feaO7N4kKZ1
zdv5QEMCpH8u1SjUF4O7XmrQikLBefCgpIbPiutDERstgxDQVLF1e54OBXir99XG
gQKBgD1uOk3bIu7802xPuIxkG09oBAo+fpwOfIqs/pOtTKtT8UPs4864CqeFt5pF
bu3hrB+7fVrDbOk2awmqSL6hY/UR5y/XFexSHvUH1o6EIr9W9DTzVx4Bq3Cs1fXf
BnkLJRwlAdmNnybcY1dUfmtSLs82YflB1jlVOFZYxLfel3YB
-----END RSA PRIVATE KEY-----"""
    }

,"mux9": {
        "key_id": "ncVUujF201n2Y5RTBv8l9efFAO00Yjc3yCUyctQxKQ02B4",
        "private_key": """-----BEGIN RSA PRIVATE KEY-----
MIIEpQIBAAKCAQEAukpCBUVBdgCJInfxXEqyDdcdCdAD3hHidtM/IgqnxMsq6s3z
5JO4IWSNHpMN5F3+MvYHPZ2hLAbt0q1GNsYNTgK0u50a29j0qLPUfoMciMKeE3uK
v1jFRflvddew/GPjYeSo4Igjo4OJr9IwMQ/hz39lR6JhfHwOhM/9equ0ASTv9W5p
S1XuCbERXRbxkBwVpyYQAfiymTlmkJ658NHeVar3jUMjdNR9swP9Jw61RpqRe8V4
/qcOGxzOah1E1y0RQafDsSsr9VVUZ62Elf6bqEcxRg/BrDOhfEMQmzeOrq2K1IEE
Ay6OT2kcl61/LWTYso3og+0MP5freXL/WoYBxQIDAQABAoIBABxQ1Dcr3zbZ/v4z
wAaYvfa3l0zaBvR2wHbyRhrdBsI1ZXkaQ/Oe9nJw77hRft+S3+QMHG6jqo9gID8R
ImaJ9RTB+Ym46A+5qvqHlwmB0VECT/fDJARQsG+h6ey+E8NRRYsoL/ktCEm+4StN
5hBXCyo4gYMBbhL3YleSq8M9HRe9LKKoX/AoXwJHIKUU7QoaVJMqV8vczZY0qozY
8rBDjD/PpcoY601ty2Ea1KMl+wbBmzD1d3/CxzrryJ/X02InD4ifK39AP/CG3jaN
1Z6yil2XuhGRtgEk9KUnTQPe1gVxgyVF5HwUZFslcw7/Z68YTJj02nQ2v/u6UdRu
Xyk7/pMCgYEA0kg4SBCyBsOAhIh/YNPFAFfyUIkY4AfJy95O7q2ufu3UCNGZ8xAd
gm6N4S5uRkf4SBkA7KRicvdVKOyGCrIY0lkht7kAe2Vq5FvtuOzuXkjOmH6JaLuY
Hs8WNj22ZOqBmcxjdjTWXGuU14W2RZzd9P07+raCz0pS8Fheouqfhc8CgYEA4sqz
YkxGTbgcC1qSWGptmpJEAOV5uNFKlBDbr2zDrq15OAHdc030s9OzrX3zJCCn6oQ5
Rh/Y4FQ8IC/aS6jDC46fnTjLEmdeJ2JXLvxp8LWmbTzfL8/70pjtAzJLrHAvx/76
fnOeGP/ic0qEZbcgjSXOOWGaSkIC9Xtaz/bG+CsCgYEAtpn8Nag5z+HJIk2dvylm
MuwsAX9r2G8q7xv3ExBDLPm9XIMW2pkt5uu1zMsS+3jXw1PjF5uP2iGpE8aAh50s
LM01mGLQZlclQXQKtMEaJUm4DXgkPoxYhrhxo1xnnK5/KFzyKd2sH8lUEOuN4llb
7LhSc141rWfvKcKzO2neaMUCgYEAqIbwHg+H/qDdViKLtWAA6mfeWLwtY4VC4hxU
41rzXo5SEahxIwm+2RJr5nQ9hY8uuDphRRbNVoXB2Dk3Ahn6NlBZk79sR9TARovx
NV0kbFbPwUUGpMTs4GX7WfC6Av2qw/dZtTW9Od6MLBgnol4etkRtpn485QmAoWJ0
7Sz4VdkCgYEAgHFxmzu3lJs7q4ESgNv5yrtNbKsSDLuFPqvj6IGI/+V30D/Dl79i
NHurWJMwcvG3KvdaZzOrfDPplKXZUn7PGN8FzAC+l7NRSv+H8vtIe9fiUazZOaIR
qpQfTXSlnvbqQtba92eQC4Au5qHpFcDqx0OK9p8ucfHI7q7wo1fXaiM=
-----END RSA PRIVATE KEY-----"""
    }

,"mux10": {
        "key_id": "T1BqpnJcULdlTXthEqfWa8kaMxAoOuJ4cpLxihFXisI",
        "private_key": """-----BEGIN RSA PRIVATE KEY-----
MIIEogIBAAKCAQEAvBJz2U9ViNEFZE7WRVtOpgoCDyOFfgQgYxz+7JekZpdUwgz0
8PmJ9y0p7TRwatB1MpPZCZhu+cNgqB2qQXaZxfjDdeBaMe1FTt/Gm5xGR55cpZIv
B/8fQMJxNdSwr/NVVVh5vWQbD2cqoOp2BqtGJsRb9SOGsKCRz0IyIKUExrC91LFK
eC0PfZR7DJia9sEiuwY6AjbRXpa4lbQoOqMJIhYVQkeClO63Z1v3OVUk5bob4jgv
n+aIfNBRd77NLZxFvb8FfRCShjOXBTgFgSpDCKdgMA/vjniB3Rkn+5MJ0Me0AB3e
pOAR81Cr6f4Ofm68Hfjg92/vAg4TRRbgdpSSxwIDAQABAoIBABrGux0NYS2Bf4sF
zmvsJrPCaQNOw2AVplF2J1/37GgkKOUX2H0WihYEUBvS2M6HBKiWyX0cPsXrPdpc
SYktzDxAwVNfBc27QkrggUkBDuB+I3f56shGAmUYn0BSxR/H5+D8H8O0ekXPImVB
UbHRYMN+4WNyvhJs9KrVed2RS69zQT7FKFAb29kTDV/pYolTaj3gb+y5yifywU7q
UQ/mQKzQ5zRuBpWY3TCHTkFSf1BK7jCW3RGLARmbN9wWI/yPgA4JrSADoVO8JMMn
kCSfLIQK1mPzKH3iNa75FIKgen1bKMngSbefobatL0zErEhb4oqouhaJVJhpPSsK
Gq7HhoECgYEA4LlVnAE83e+N8lkKO7ZtjCRdCH5/EOnyabo31jQHXpMKj+BSbY0G
TZgpcXEhVMCB7SQPaWQlKKfxec8ndAxiKhX2vjZCnKpKfYxSqTlOsqergGnACSbz
HD7Jf5Cvin4CDe/7WxO2dqCc6Fs3ZHGaXxd25IsAS1ohEi/vrWszB58CgYEA1j9A
kBp9uuTmrVko5mIvM31F0v3arnuana6cJbNwjplkFc7T7e9pw3hNQr8uv1B4iQDk
bjTNhSo1D/DJGPbXuPOtx483R4b2sb7LhC+7fK7GUx0wK+GhZNq0hz7tO+z+G91n
Hbm7PTUsnN+oyNw+hIApnstPEZLEibVUHHxbw9kCgYAk3WJ04CMbCVRQ4Fh0aT3Z
UpHMdevkW2x/+aN1ST24Pwjph1QeUpcpHYAW8wcTvyzROSwqDtqlq79KSzheqjVk
UAwVMhOFXc4wgFeDGTqWxji1LSPqnHAfPxGREqwpXPh7TtX+H+K73SdAWs5gdN5t
IQ1I+qCGu/dW43Q/D6nkYwKBgADNCbvALZomQuqA+9MoqM6DeGBajJe8ZI6UWYcW
jaQq1KH0PPyVuYp+h6NpPY5/iYPRmgkDb4VA7CPcHZRXT+UkHBEz6tv8mC1/7hjX
aNcFfD5RTJ3NYSIUYzpiNNbVgvmtsTX+PMH00e7gMyxVDnLGW+F5FxmUt+Ff6SmW
GW25AoGAUpxPTk4NxHrMV2Oa04gFIF7r/IKitnaYcAklETSiWTijuy+Sf4nwoRbx
xG6bkfATjfKzsGr+knvVDqkv46xWCbflO2OMGkff4uepnB97eWDHbXk6wst8ua2W
lDhHUoiLR1GBU6+49qDNWvoFfr+IF4DFEE7mvQfQ5/zUQkz3FD8=
-----END RSA PRIVATE KEY-----"""
    }

,"mux11": {
        "key_id": "TLuIhVbetutBAW3GcjcGNiNLYFH1VWR4v6bo02rmkOO8",
        "private_key": """-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEA2IJs/D4GV1LuH9jI2K52PB9ioKM03rph3ye9dhY1IVq5jrRN
b1EMPiPQxOWxSOFoukTavB6KNSygjOHJ6BU8Feo2dHWMOf3LR6+/uz/kTd261EFp
Wsq1hjhachTNJcFmGnCTnE9ZTT9uC6LTb1eVxoO2qwgZQNSJwzK7ZmC3+gv0ZCYU
TOH/loV19RLWNOr/kcKyOwOO8vKWEljHpxq0Ajv54qDjbdnwVTmlXKZRTV+hZGp2
Na4heDb6NVavfaoPr2z3YyZquiBk7VpfcvOvCv6LmReEWy/Iq+MydDA+DrTVNwgC
wMa+88PizMq4652tXC/fHzxWyQjic1qPyIvTZwIDAQABAoIBAA/F7LexsxeQiJ2U
VwmGKEH4DWDjkvn4/SFbTU+5jXRZHjSZyRxnfKtYQ6DclP5YwZ70XjUfSnVWQ3oQ
Bvwb8+0qy33PhIBDD5iw4ph7LqBHm5FUFJ9TLkdRerFd95YdEVmywuY716crjFJX
seymJli4hsnOBLz23vR0ETgDqtOSAg8z0uFvDWzFchhQu0UPoK5H6pp+mOYb7aVB
l7dgYx4ZVq9vk60n2LVnhQk8xj3a/87AksTrvNcYX4kvLzCvMZHb7/efxo9cySDa
5wgxOoUgfmcNy/cv8lqNdNcP6AakMwj1VuK1g3Li5KxnqRLRxwaiKQ51gpuqLxLp
hmq7osECgYEA4nVcVrER5r+YmnqJPXBzums1/sIlGpzWORllEsqhJ/qcQ5wBe5P/
CrZ6KoCUUjvdb5jXh4EK4ZGKglqUkWoLObODhvfHZChOgEhxhgYYnUC+UaaIefaR
nT9Ttn8nVEmBiXQKRwTnlyUx38cBDASClpCCoFRH1Ch0/af6iF+gdKcCgYEA9MDR
FPc1aolLBJ3at2veCw9ofPlaqqrWN4l+aw61oGDtY7dJh7br7ZGnI/UlnypSJNU7
StlJDMIfGMlSD+2xGyYOLUlByzvTGZyERIW/Vmb54LKOBVO0vZ0zzYlGn3rR45mT
7R0WPV3mdQ1v8lAEjQdKSGJQz3Pl6q/xsR/Vw0ECgYA7JKOFEKG4PfnA/pexMBlJ
ao6jhljiZmucZgF7suf75PvCvI+2kqRdS+MEDqiuAWyHpMdFYHJTDwu5l6aNg8CC
xVtoeHXetpgp8MGVWyo6h5otAO1LzRWil9NpKjQ/UyM9nszAV4uUceZgpzyiwtrI
L92tudU4l4hWZvSLgU4KqQKBgQDZN9dYOB5cMwU1T7OxXjZusnoVkGh7V6tPFuPv
t9pSQDPvb9f+bsXsznv8WbHOFQ1aSzSYNUez3wUiRmpiYJ3ybk/euUl/SdUMwfBR
sDIkSLg0R8PrzmJ2dnJnVBItsB9fVAoJQuteA1xpPkfAUmv3jiTLIRZ/R2kiZIyo
moxpAQKBgQCdX8IMsbAB2DiSagagjkuJjgtZp5FQS5cdzAdOlIKVMDt4b9wA25o/
yWvcMWmdymByrbQx3y6Dft1SM5NsQfJRCoUGQKjBM3qL6zfy4q7hWjKUBB70VzC4
FafrCOjVk7mvRUsOsvI/UAq04omI3D420d+j7PWsM2UCTZsXG6chuA==
-----END RSA PRIVATE KEY-----"""
    }

,"mux12": {
        "key_id": "367ja6vsxBThn02OgvPy22qtJTRPrJssMNq5D5xgwT01g",
        "private_key": """-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEA4t7p9DSMM4R60CyK0/blo51GEg11TJpYYAVPMYXP/7Tpx5yW
iZGvt+sDgpvlnE3igfHavDJhvNv7Ua1Hw7o1Y11piE3o0ZHWfOQt1vWiAwYuqeO5
N+7bdxQiEXNGgsNwa9zrbx6qFQBH+cJUIlv6SaREvIhRs+2si+VOVLqvE/L9w4/4
4Ddg/hcfTMLfwm6hco9/3Z1d3EHRBVka4wi/aXzVgjuYouMwEd7zbE964+7ORiPO
ib3fSpnUgWDbb3VVcun27gbfyNYHPvuYuX9lSxNkqy+gMzB9eQRTnCeSNr99rrP2
V9fz7Ywp8aJg0nn1NrWT3ub4dlHl+90M3G44nQIDAQABAoIBADoYNvSP2C8BB6nz
HgG1QYyqI11QEO9yvpqoAWV/DIpAO3UgBfRoWATSq21wmlVyJER+ODLk+94uvqZl
pvDZ5/3v16xNtwajP7dvfsWC1N/NX3mllLJb+dr+TtMFH9MwVMNqKOelhIwoLEYq
mvzJbMgaxnc4uSNIA103dN2BiH+kyCXTvW5qgM0ef53AzqL3zmvBA2mRXXdaYgnl
fhYdfXIzPQayMv9AcWdD30QRaveSlyZBRGTq00YwNCj+dczXbuwRjF6bR0A0NtSz
fInKVv+wxdfnpkwQzQHR8BHjpp0iGz+H+ksmqvyT35dLjtN1LME3PcYom7he4kxr
tTNNQ0kCgYEA8TeUoaajA1S308+fFxGhwCCWCDPe7+cqCUsxdYXvKjTNLSO7snTY
iiPdXX1YEUspOusNZoR4p/Pthsnz/qAHGnryExQUXgRW391xV+0ikRiYqUH5jp6v
vfrhY5kATWUSKS5QA2mz9T9FlVdQK0gkmti74rqtpcrgPkQAJQckTGMCgYEA8MZB
ZoHqx2lA1fb8XEvHVjyoS8hNSW1kRnTv966/hv5PFBEE1Ly1q8Lof9DAkn562S2A
O1KAEJt6gf2OQfU2V3i1Z45KZ7iLnb3TFuPfHsp6Z1Fz2JgGc7rN4Wa1R6zH5cKD
1VmUBXcaP54l0R7CU9UNM9nGw5Fw8XgB+stV9v8CgYA8cmgtpht9jzJNwt6kIkf9
ZG0UeyMnzS7si0pGoByR4A92e1ji3IMTAu/LKMjz9HjNie+evB2cQPVJ7LvXF/UP
vrWA8Gw2LzIyAUUQ+pzJ7Xb8G0tVYRC7M+5dTg8UVfqaFT/5yvhMweFHDk1Ju1do
8l0K8SrovBE7qUC8BrEi7wKBgQDl3PA9E9T3sZVzcAt3deUFgH1PdBfM/QGZfjRG
au9wykLmrmTFUK/EHhznQX1HnjZcNmNQvy+CK10m0tHISHkrwxK0nZSNNxMbckkf
dkbh135KOun1IxYt0G6TPQHePqbMxAomWhHFsfI+QBZscggmDqU/Fi77MFP6Q47o
Rs14MwKBgQDEf2HGI2FXe6ab96YAaPx1WskpTkXuRwW7kUraof4xLPXyZsZDlQ8k
Fbzfp1ih14yv1jVmbMCUpcVB4sILFtcEKd+gkdeHTYyU1VvBEUDN7VvVh5+mWlJD
NPFClmvJcin23I41VRRXfSOuWri2AqJZLnRbhCfrr8cja1riChWNRQ==
-----END RSA PRIVATE KEY-----"""
    }
}