"""
Django settings for SLMproject project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-%a_htvvnfx_k0yi*cgmzbu0^t62$zezoyje-07*0!r)oo1rsvx"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["slmpro.pythonanywhere.com","192.168.1.60"]


# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "SLMapp",
    "rest_framework",
    "accounts",
    'rest_framework_simplejwt.token_blacklist',
     "corsheaders",
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}
AUTH_USER_MODEL = "accounts.CustomUser"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
]

ROOT_URLCONF = "SLMproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "SLMproject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

# Source folders for static files (development)
STATICFILES_DIRS = [
    BASE_DIR / "SLMapp" / "static",  # only your app's static folder
]

# Target folder for collectstatic (production)
STATIC_ROOT = BASE_DIR / "staticfiles"

from datetime import timedelta
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=8),   # 8 hours
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),   # you can adjust (default 1 day)
    "ROTATE_REFRESH_TOKENS": False,                # optional
    "BLACKLIST_AFTER_ROTATION": True,              # optional
}
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
     "http://192.168.1.60:5173",
]

# CORS_ALLOWED_ORIGINS = [
#    "https://slmfront.vercel.app/"
# ]

CORS_ALLOW_ALL_ORIGIN = True
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"





MUX_ACCOUNTS = {

    "mux1": {
        "key_id": "8p8bq00YDZ6uharwJ01yTqHiv2exqhrxRRzCWeiaMNinI",
        "private_key": """-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAqW7QHcgX175WbPEPgNx3H+genNhwqdWayAwbE/HAecrjPdZ2
8pIoWjo1vYq9sWHiDvmDKfdPn0IVwjVbZDFYEu4VrQB7XjryncS/xoyDutqbWKxi
I9w8mdtqfqP5HGBYyRwPFagJvl6eTEDvwo8BdqX6fvtANiN6DMuK0LpaqwW65jp8
wItNH7rFbn71pGa6+/JxmlbMre6MXAO0nkH7otSY/JIDOyUTtGXDfdGbJVMDvTA1
vblU9NcKSudMS5/nHJK56SkUVX4AaDqGO+UtFC9O+isKxNBx/J6vu2Ftj9jwwgNs
Q0oRve07b1SFXr2UjwOARcwp3fH8k4yCzUObbQIDAQABAoIBABkERBVJoH+Z2m/u
beAUbUBYSQDWklf5MofcBbl9pfI1qzTLsDdjrjKYSqwISrbgoXydiajOG8MDgmvw
7eQOxxbQcYHgQtbodD8oODqsL50MvwgqN7lcwNPkykYVlugCL8nN60pCy+GAXfYb
VmtPKyOmISTTmykDNvehrAbipRWAHv5ShdDhHHiyiZVMae2oI+lil77DkPxEbxJ5
o3ZP+03AQWFo91eO0e7Gbt6CD3KWpLu6LQfS+if5YFaVOrfUCkafFRKdmbBjHam+
r9xiDSCdBBHuCBCBKwzl3G6LFmExZ65udZ1IuK/nV6ixLuO/VFB6Y23OutrQdwK1
YPGzzw8CgYEA3CMCkXFvaVtfZ1Sq4aospDIDgiV7LkJkwS7FINh8yC3S9cNMrAH0
5ewWB7pKL6tumSzxoBT17aVq3I9svLOFpWnBYXZDVvdCu1IodX2BPPj7ywj3QVUb
GiQHDIvHtsfdF7gD6uX1hf3YP02DhyPc4MdhKeOp7BfNnm9u+93DGccCgYEAxQkn
bvt744HtENPkeYNb5dTizUrkAxAAzz14MyFw+cpWkhNxbDco+ElGJxH8VFLGXfyz
3qoFDeQJlSmc1vhyq1h87thWeSbq4egsc8rkodGtOH3WwUl5OIVFoPq6WWyfzEqq
aKzBSx2JVgc0ur4y4r55nHJLSIOOti55ya53gSsCgYAJQrvH7JK4RuzDhw9NQQBx
w9zb68G713Uvn00RranKLgtS5W1jSw3HYmAm4RJf4QFdFkPv7RHPdocBUlNLuO2l
YMaO2A/LJ8m54aHsF2SJcRv+lZj5OaBTQDK/t12mdc/6QHaBujzS7zPareMbm0me
dyTCQ16RnQq8YIm1tMWRXwKBgDdplqR4p2PZQ1GLNeMSlUKyt0IjALL3yjJ+SBKh
IgOt6uDUBP75GFWTTd5pCXyxdsYx7mf9isRYUHWZqVkvsBgOH7yQLOmPj1kPEYlT
Ey+LJ1sO0Nm1DxldKbLXMJc7nEk46mnbw9SbLud5yVOHcAoipVLhNdjj3rvPoEKf
BU7XAoGBAMJQrGUdqjxmnybVM2SGpHyf4bKUPn+4lbqml5lAMRtIUUinLcLppdHh
oemma4Sm+yOhXYDvN3yY1WTCAPlQ+WE/m117+PL47FIfeT5LkExlgpiqZYlDRrzy
8FyKyMZk7vU44ahmmUR7wm9Ya+W/YEPidLIzbF3FU87Yiw/JBOou
-----END RSA PRIVATE KEY-----"""
    },

    "mux2": {
        "key_id": "WI8ksNcJhN6Jv9uNP38i01dNbFXN023L86V48jKcQxeV00",
        "private_key": """-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEA15oVp9leKyTyX6+vFPgS10AXIvfI6M+pGpYszSc1pube/pZd
PfdiTNyzHWX7llVGUkThOLMZJ2O977iV988xlTg0xswTf6Gj0kgiYFB1RjPHTYey
EHP0ovHPkx7OwokgMvKSEUtIliiql0y4E/jU1ZXPmHGQwXBmLLauLY/leAF4WS+E
Df2SebanRx/fp15Bq61qRe/LqFJHBv7FN3fyj+kWilTZpfdHHwWOxvSy9bUpNQ7R
dVFXxidvo2WujFWZtbHaJfG4IiyaagjwtaNhfoPlKpt8FOMNLBeu3X+tT+vOMpUv
B1Rw8ysYuMEiwkCoxX+oXvggUIEpXrU/vwp9DwIDAQABAoIBACzO8MZAJlKYLKlX
VW9puVy0DLrvPXmpQu9sG6aNihiEbf8CWCGbSvpHehBXlCij02gguaAzlLw7fguW
1NA6ZwcotctFOZ4yhV4cMMzMm/r5oufJlmfV+Zdt4yKj6fvDTQZZpKLkfxL6I64r
Oyynb/Bt4MXBgIC7b/jGBMAiYmIEpkF7Az6hEpdII+6aHfsgU+ASdPHCAMV9EXQ7
Xw2HV5ySBevG70uJ6u7xkMAjcNbSPVLSTbLUH2p+x58bU8Qofac53rU/jUq7482q
xVFd2CZRbW+w0Z14qHbg1VokWKSj47EVbY0z75QzAecgw8ZS0wOTNLHarmiGGMb3
/W3zNfkCgYEA/byD+D762IuF1G6zb0ANIuvlyXnkiH1lC/GHVwIcL5kcDGcOCtwr
KDKex6LBYAe34VLduPTYwycKYsjGpSyC5wSSSl/GnzkRZ/M0MKuFJLukyQS5x02+
xyCNOEOOlZIKHZpOej+1ctcB98kgmhnfSgI9bN5O7wvg/Tu4FnLEmikCgYEA2YZ6
MfI1RZdEmf6pV+ZDY+OgGfwFDM1/rx6pIQmHru4WOm+Rqu1ypZMpcg09EdZCS0Zi
9+iSU0vugG/r/vZIfbaq3QxfeCjFhL01UfZ+LViaHg2v/LOgjHXqhW5juovF4q89
3rDLZn75i/QPQhbpveWCQzntcTlqC8UmG8tytHcCgYEAoqHwHG+RrLZRA0YpMIdn
ZBi7YhYEyw9EcxFOZBBwLHoAplpvf7p61vsLFn5VX83SqFPK1b/qJ7ugRozV9gy/
on8lnRIiZu/XHj+eFgv5/P9gsY+b3AkS3OMaYRO8ElZWsX60CltHW+I/2qhJgzxO
CEvDP0KGaWW9wdJDPfA133ECgYBL2u9l13boS7XqlbnsIypA/THpnc8NBeSO5vxH
vxEH2ZL60clUd/VQ9B6x3Rf8zmDT6zm8BehxD7ueImmDwdLJtBelehkYx+8JOQoN
CQ47NfiYnmFOmD1WfhBIc5RnizJ4uG+05qYnmgPf4D4p59+fDxf75Yl9wG3QqPF/
I9VeRQKBgBwQ2SoQiP22VRlsVXK02Th89QzU1KCZ0LMdw+aNNOwknt6lci0FnA/u
a8OTn/685iep6Ib3wOQkkVdsBVLossdgbE35eC6Wb3PhRDl65EpEsaZLm3pqB6FC
hovRRCIMTv0e6DlXkEoEh+cP2+5DAI1QgPhuE2UlHEzC0sMSZBme
-----END RSA PRIVATE KEY-----"""
    }

}