# Generated by Django 5.2.1 on 2025-09-30 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SLMapp", "0003_maincontentprogress_pageprogress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="topic",
        ),
        migrations.AddField(
            model_name="quiz",
            name="main_content",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz",
                to="SLMapp.maincontent",
            ),
        ),
    ]
