# Generated by Django 5.2.1 on 2025-10-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SLMapp", "0004_remove_quiz_topic_quiz_main_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="title",
            field=models.CharField(blank=True, default="Untitled Page", max_length=200),
        ),
    ]
