# Generated by Django 5.2.1 on 2025-10-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SLMapp", "0005_page_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="prize",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
