# Generated by Django 5.2.1 on 2025-10-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SLMapp", "0006_topic_prize"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="difficulty_level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("hard", "Hard"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="time_duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
