# Generated by Django 5.2.1 on 2025-10-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SLMapp", "0007_module_difficulty_level_module_time_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="module",
            name="time_duration",
        ),
    ]
