# Generated by Django 5.2.1 on 2025-10-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SLMapp", "0008_remove_module_time_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="time_duration",
            field=models.PositiveIntegerField(
                default=0, help_text="Duration in minutes"
            ),
        ),
    ]
