# Generated by Django 5.2.1 on 2026-02-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SLMapp", "0009_page_time_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="video_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
