# Generated by Django 5.2.1 on 2026-02-14 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_customuser_username_alter_customuser_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="topics",
        ),
    ]
