# Generated by Django 5.2.1 on 2026-02-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_customuser_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
