# Generated by Django 5.2.1 on 2026-02-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SLMapp", "0010_page_video_id"),
        ("accounts", "0005_studentprofile_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="topics",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="SLMapp.topic"
            ),
        ),
    ]
