# Generated by Django 5.2.1 on 2026-02-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_customuser_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="professionalprofile",
            name="interest",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="passing_year",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
