# Generated by Django 5.2.1 on 2026-02-19 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_feedback_supportconversation_supportmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="feedback_type",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="page",
        ),
        migrations.AlterField(
            model_name="feedback",
            name="rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
