# Generated by Django 5.2.1 on 2026-02-20 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_usercertificate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercertificate",
            name="topic",
        ),
    ]
