# Generated by Django 5.2.1 on 2026-02-20 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SLMapp", "0010_page_video_id"),
        ("accounts", "0011_remove_usercertificate_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercertificate",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="SLMapp.topic",
            ),
        ),
    ]
