# Generated by Django 5.2.1 on 2026-04-02 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_usercertificate_topic"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLastPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_id", models.IntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="last_page",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
