# Generated by Django 5.2.1 on 2026-06-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_userlastpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="module",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
